gitops-runtime:
  global:
    codefresh:
      accountId: 647d8f6adafd9dc9fcf7f73b
      url: https://pre-prod.codefresh.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - hermes-alina.rnd-sandbox.cf-infra.com
        protocol: https
      name: test-date
  installer:
    skipValidation: true
